/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculadoraOxyRouteImport } from './routes/calculadora.oxy'
import { Route as CalculadoraCfoRouteImport } from './routes/calculadora.cfo'
import { Route as CalculadoraBpoRouteImport } from './routes/calculadora.bpo'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraOxyRoute = CalculadoraOxyRouteImport.update({
  id: '/calculadora/oxy',
  path: '/calculadora/oxy',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraCfoRoute = CalculadoraCfoRouteImport.update({
  id: '/calculadora/cfo',
  path: '/calculadora/cfo',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraBpoRoute = CalculadoraBpoRouteImport.update({
  id: '/calculadora/bpo',
  path: '/calculadora/bpo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/resultados': typeof ResultadosRoute
  '/servicos': typeof ServicosRoute
  '/calculadora/bpo': typeof CalculadoraBpoRoute
  '/calculadora/cfo': typeof CalculadoraCfoRoute
  '/calculadora/oxy': typeof CalculadoraOxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/resultados': typeof ResultadosRoute
  '/servicos': typeof ServicosRoute
  '/calculadora/bpo': typeof CalculadoraBpoRoute
  '/calculadora/cfo': typeof CalculadoraCfoRoute
  '/calculadora/oxy': typeof CalculadoraOxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/resultados': typeof ResultadosRoute
  '/servicos': typeof ServicosRoute
  '/calculadora/bpo': typeof CalculadoraBpoRoute
  '/calculadora/cfo': typeof CalculadoraCfoRoute
  '/calculadora/oxy': typeof CalculadoraOxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostico'
    | '/resultados'
    | '/servicos'
    | '/calculadora/bpo'
    | '/calculadora/cfo'
    | '/calculadora/oxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostico'
    | '/resultados'
    | '/servicos'
    | '/calculadora/bpo'
    | '/calculadora/cfo'
    | '/calculadora/oxy'
  id:
    | '__root__'
    | '/'
    | '/diagnostico'
    | '/resultados'
    | '/servicos'
    | '/calculadora/bpo'
    | '/calculadora/cfo'
    | '/calculadora/oxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  ResultadosRoute: typeof ResultadosRoute
  ServicosRoute: typeof ServicosRoute
  CalculadoraBpoRoute: typeof CalculadoraBpoRoute
  CalculadoraCfoRoute: typeof CalculadoraCfoRoute
  CalculadoraOxyRoute: typeof CalculadoraOxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora/oxy': {
      id: '/calculadora/oxy'
      path: '/calculadora/oxy'
      fullPath: '/calculadora/oxy'
      preLoaderRoute: typeof CalculadoraOxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora/cfo': {
      id: '/calculadora/cfo'
      path: '/calculadora/cfo'
      fullPath: '/calculadora/cfo'
      preLoaderRoute: typeof CalculadoraCfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora/bpo': {
      id: '/calculadora/bpo'
      path: '/calculadora/bpo'
      fullPath: '/calculadora/bpo'
      preLoaderRoute: typeof CalculadoraBpoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  ResultadosRoute: ResultadosRoute,
  ServicosRoute: ServicosRoute,
  CalculadoraBpoRoute: CalculadoraBpoRoute,
  CalculadoraCfoRoute: CalculadoraCfoRoute,
  CalculadoraOxyRoute: CalculadoraOxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
